version: "3.9"
services:
  blog-service:
    build:
      context: .
      dockerfile: .Dockerfile
    container_name: blog-service
    volumes:
      - /home/ubuntu/book/pdf:/app/book/pdf
      - /home/ubuntu/book/cover/:/app/book/cover/
      - /home/ubuntu/article/cover/:/app/article/cover/
      - /home/ubuntu/user/logo/:/app/user/logo/
      - /home/ubuntu/blog/static/:/app/blog/static/
      - /home/ubuntu/backup/:/app/backup/
    ports:
      - "443:80"
