apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      imagePullSecrets:
        - name: dockerhub-credentials
      containers:
      - name: data-service
        image: data-service:latest
        ports:
          - containerPort: 80
            protocol: TCP
        env:
          - name: MYSQL_SERVICE
            value: "mysql-service"
          - name: ELASTICSEARCH_SERVICE
            value: "elastic-search-service"
        envFrom:
          - configMapRef:
              name: configmap
        resources:
          requests:
            memory: "100Mi"
            cpu: "0.1"
          limits:
            memory: "1Gi"
            cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: data-service
spec:
  selector:
    app: data-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
